#
# Module manifest for module 'Microsoft.Graph.Groups'
#
# Generated by: Microsoft Corporation
#
# Generated on: 12/20/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Groups.psm1'

# Version number of this module.
ModuleVersion = '2.34.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '50bc9e18-e281-4208-8913-c9e1bef6083d'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.34.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Groups.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Groups.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgGroupFavorite', 'Add-MgGroupToLifecyclePolicy', 
               'Confirm-MgGroupGrantedPermissionForApp', 
               'Confirm-MgGroupMemberGroup', 'Confirm-MgGroupMemberObject', 
               'Confirm-MgGroupSettingTemplateMemberGroup', 
               'Confirm-MgGroupSettingTemplateMemberObject', 'Get-MgGroup', 
               'Get-MgGroupAcceptedSender', 'Get-MgGroupAcceptedSenderByRef', 
               'Get-MgGroupAcceptedSenderCount', 'Get-MgGroupById', 
               'Get-MgGroupByUniqueName', 'Get-MgGroupConversation', 
               'Get-MgGroupConversationCount', 'Get-MgGroupConversationThread', 
               'Get-MgGroupConversationThreadCount', 
               'Get-MgGroupConversationThreadPost', 
               'Get-MgGroupConversationThreadPostAttachment', 
               'Get-MgGroupConversationThreadPostAttachmentCount', 
               'Get-MgGroupConversationThreadPostCount', 
               'Get-MgGroupConversationThreadPostExtension', 
               'Get-MgGroupConversationThreadPostExtensionCount', 
               'Get-MgGroupConversationThreadPostInReplyToAttachment', 
               'Get-MgGroupConversationThreadPostInReplyToAttachmentCount', 
               'Get-MgGroupConversationThreadPostInReplyToExtension', 
               'Get-MgGroupConversationThreadPostInReplyToExtensionCount', 
               'Get-MgGroupCount', 'Get-MgGroupCreatedOnBehalfOf', 
               'Get-MgGroupDelta', 'Get-MgGroupExtension', 
               'Get-MgGroupExtensionCount', 'Get-MgGroupLifecyclePolicy', 
               'Get-MgGroupLifecyclePolicyByGroup', 
               'Get-MgGroupLifecyclePolicyCount', 'Get-MgGroupMember', 
               'Get-MgGroupMemberAsApplication', 'Get-MgGroupMemberAsDevice', 
               'Get-MgGroupMemberAsGroup', 'Get-MgGroupMemberAsOrgContact', 
               'Get-MgGroupMemberAsServicePrincipal', 'Get-MgGroupMemberAsUser', 
               'Get-MgGroupMemberByRef', 'Get-MgGroupMemberCount', 
               'Get-MgGroupMemberCountAsApplication', 
               'Get-MgGroupMemberCountAsDevice', 'Get-MgGroupMemberCountAsGroup', 
               'Get-MgGroupMemberCountAsOrgContact', 
               'Get-MgGroupMemberCountAsServicePrincipal', 
               'Get-MgGroupMemberCountAsUser', 'Get-MgGroupMemberGroup', 
               'Get-MgGroupMemberObject', 'Get-MgGroupMemberOf', 
               'Get-MgGroupMemberOfAsAdministrativeUnit', 
               'Get-MgGroupMemberOfAsGroup', 'Get-MgGroupMemberOfCount', 
               'Get-MgGroupMemberOfCountAsAdministrativeUnit', 
               'Get-MgGroupMemberOfCountAsGroup', 
               'Get-MgGroupMemberWithLicenseError', 
               'Get-MgGroupMemberWithLicenseErrorAsApplication', 
               'Get-MgGroupMemberWithLicenseErrorAsDevice', 
               'Get-MgGroupMemberWithLicenseErrorAsGroup', 
               'Get-MgGroupMemberWithLicenseErrorAsOrgContact', 
               'Get-MgGroupMemberWithLicenseErrorAsServicePrincipal', 
               'Get-MgGroupMemberWithLicenseErrorAsUser', 
               'Get-MgGroupMemberWithLicenseErrorCount', 
               'Get-MgGroupMemberWithLicenseErrorCountAsApplication', 
               'Get-MgGroupMemberWithLicenseErrorCountAsDevice', 
               'Get-MgGroupMemberWithLicenseErrorCountAsGroup', 
               'Get-MgGroupMemberWithLicenseErrorCountAsOrgContact', 
               'Get-MgGroupMemberWithLicenseErrorCountAsServicePrincipal', 
               'Get-MgGroupMemberWithLicenseErrorCountAsUser', 
               'Get-MgGroupOnPremiseSyncBehavior', 'Get-MgGroupOwner', 
               'Get-MgGroupOwnerAsApplication', 'Get-MgGroupOwnerAsDevice', 
               'Get-MgGroupOwnerAsGroup', 'Get-MgGroupOwnerAsOrgContact', 
               'Get-MgGroupOwnerAsServicePrincipal', 'Get-MgGroupOwnerAsUser', 
               'Get-MgGroupOwnerByRef', 'Get-MgGroupOwnerCount', 
               'Get-MgGroupOwnerCountAsApplication', 
               'Get-MgGroupOwnerCountAsDevice', 'Get-MgGroupOwnerCountAsGroup', 
               'Get-MgGroupOwnerCountAsOrgContact', 
               'Get-MgGroupOwnerCountAsServicePrincipal', 
               'Get-MgGroupOwnerCountAsUser', 'Get-MgGroupPermissionGrant', 
               'Get-MgGroupPermissionGrantCount', 'Get-MgGroupPhoto', 
               'Get-MgGroupPhotoContent', 'Get-MgGroupRejectedSender', 
               'Get-MgGroupRejectedSenderByRef', 'Get-MgGroupRejectedSenderCount', 
               'Get-MgGroupSetting', 'Get-MgGroupSettingCount', 
               'Get-MgGroupSettingTemplateById', 'Get-MgGroupSettingTemplateCount', 
               'Get-MgGroupSettingTemplateDelta', 
               'Get-MgGroupSettingTemplateGroupSettingTemplate', 
               'Get-MgGroupSettingTemplateMemberGroup', 
               'Get-MgGroupSettingTemplateMemberObject', 
               'Get-MgGroupSiteGetByPathApplicableContentTypeForList', 
               'Get-MgGroupSiteGetGraphBPrePathActivityByInterval', 
               'Get-MgGroupThread', 'Get-MgGroupThreadCount', 
               'Get-MgGroupThreadPost', 'Get-MgGroupThreadPostAttachment', 
               'Get-MgGroupThreadPostAttachmentCount', 
               'Get-MgGroupThreadPostCount', 'Get-MgGroupThreadPostExtension', 
               'Get-MgGroupThreadPostExtensionCount', 
               'Get-MgGroupThreadPostInReplyToAttachment', 
               'Get-MgGroupThreadPostInReplyToAttachmentCount', 
               'Get-MgGroupThreadPostInReplyToExtension', 
               'Get-MgGroupThreadPostInReplyToExtensionCount', 
               'Get-MgGroupTransitiveMember', 
               'Get-MgGroupTransitiveMemberAsApplication', 
               'Get-MgGroupTransitiveMemberAsDevice', 
               'Get-MgGroupTransitiveMemberAsGroup', 
               'Get-MgGroupTransitiveMemberAsOrgContact', 
               'Get-MgGroupTransitiveMemberAsServicePrincipal', 
               'Get-MgGroupTransitiveMemberAsUser', 
               'Get-MgGroupTransitiveMemberCount', 
               'Get-MgGroupTransitiveMemberCountAsApplication', 
               'Get-MgGroupTransitiveMemberCountAsDevice', 
               'Get-MgGroupTransitiveMemberCountAsGroup', 
               'Get-MgGroupTransitiveMemberCountAsOrgContact', 
               'Get-MgGroupTransitiveMemberCountAsServicePrincipal', 
               'Get-MgGroupTransitiveMemberCountAsUser', 
               'Get-MgGroupTransitiveMemberOf', 
               'Get-MgGroupTransitiveMemberOfAsAdministrativeUnit', 
               'Get-MgGroupTransitiveMemberOfAsGroup', 
               'Get-MgGroupTransitiveMemberOfCount', 
               'Get-MgGroupTransitiveMemberOfCountAsAdministrativeUnit', 
               'Get-MgGroupTransitiveMemberOfCountAsGroup', 
               'Invoke-MgForwardGroupConversationThreadPost', 
               'Invoke-MgForwardGroupConversationThreadPostInReplyTo', 
               'Invoke-MgForwardGroupThreadPost', 
               'Invoke-MgForwardGroupThreadPostInReplyTo', 'Invoke-MgGraphGroup', 
               'Invoke-MgRenewGroup', 'Invoke-MgReplyGroupConversationThread', 
               'Invoke-MgReplyGroupConversationThreadPost', 
               'Invoke-MgReplyGroupConversationThreadPostInReplyTo', 
               'Invoke-MgReplyGroupThread', 'Invoke-MgReplyGroupThreadPost', 
               'Invoke-MgReplyGroupThreadPostInReplyTo', 
               'Invoke-MgRetryGroupServiceProvisioning', 
               'Invoke-MgSubscribeGroupByMail', 'New-MgGroup', 
               'New-MgGroupAcceptedSenderByRef', 'New-MgGroupConversation', 
               'New-MgGroupConversationThread', 
               'New-MgGroupConversationThreadPostAttachment', 
               'New-MgGroupConversationThreadPostAttachmentUploadSession', 
               'New-MgGroupConversationThreadPostExtension', 
               'New-MgGroupConversationThreadPostInReplyToAttachment', 
               'New-MgGroupConversationThreadPostInReplyToAttachmentUploadSession', 
               'New-MgGroupConversationThreadPostInReplyToExtension', 
               'New-MgGroupExtension', 'New-MgGroupLifecyclePolicy', 
               'New-MgGroupMember', 'New-MgGroupMemberByRef', 'New-MgGroupOwner', 
               'New-MgGroupOwnerByRef', 'New-MgGroupPermissionGrant', 
               'New-MgGroupRejectedSenderByRef', 'New-MgGroupSetting', 
               'New-MgGroupSettingTemplateGroupSettingTemplate', 
               'New-MgGroupThread', 'New-MgGroupThreadPostAttachment', 
               'New-MgGroupThreadPostAttachmentUploadSession', 
               'New-MgGroupThreadPostExtension', 
               'New-MgGroupThreadPostInReplyToAttachment', 
               'New-MgGroupThreadPostInReplyToAttachmentUploadSession', 
               'New-MgGroupThreadPostInReplyToExtension', 'Remove-MgGroup', 
               'Remove-MgGroupAcceptedSenderDirectoryObjectByRef', 
               'Remove-MgGroupByUniqueName', 'Remove-MgGroupConversation', 
               'Remove-MgGroupConversationThread', 
               'Remove-MgGroupConversationThreadPostAttachment', 
               'Remove-MgGroupConversationThreadPostExtension', 
               'Remove-MgGroupConversationThreadPostInReplyToAttachment', 
               'Remove-MgGroupConversationThreadPostInReplyToExtension', 
               'Remove-MgGroupExtension', 'Remove-MgGroupFavorite', 
               'Remove-MgGroupFromLifecyclePolicy', 
               'Remove-MgGroupLifecyclePolicy', 
               'Remove-MgGroupMemberDirectoryObjectByRef', 
               'Remove-MgGroupOnPremiseSyncBehavior', 
               'Remove-MgGroupOwnerDirectoryObjectByRef', 
               'Remove-MgGroupPermissionGrant', 'Remove-MgGroupPhoto', 
               'Remove-MgGroupPhotoContent', 
               'Remove-MgGroupRejectedSenderDirectoryObjectByRef', 
               'Remove-MgGroupSetting', 
               'Remove-MgGroupSettingTemplateGroupSettingTemplate', 
               'Remove-MgGroupThread', 'Remove-MgGroupThreadPostAttachment', 
               'Remove-MgGroupThreadPostExtension', 
               'Remove-MgGroupThreadPostInReplyToAttachment', 
               'Remove-MgGroupThreadPostInReplyToExtension', 
               'Reset-MgGroupUnseenCount', 'Restore-MgGroupSettingTemplate', 
               'Set-MgGroupLicense', 'Set-MgGroupPhotoContent', 
               'Test-MgGroupProperty', 'Test-MgGroupSettingTemplateProperty', 
               'Update-MgGroup', 'Update-MgGroupByUniqueName', 
               'Update-MgGroupConversationThread', 
               'Update-MgGroupConversationThreadPostExtension', 
               'Update-MgGroupConversationThreadPostInReplyToExtension', 
               'Update-MgGroupExtension', 'Update-MgGroupLifecyclePolicy', 
               'Update-MgGroupOnPremiseSyncBehavior', 
               'Update-MgGroupPermissionGrant', 'Update-MgGroupSetting', 
               'Update-MgGroupSettingTemplateGroupSettingTemplate', 
               'Update-MgGroupThread', 'Update-MgGroupThreadPostExtension', 
               'Update-MgGroupThreadPostInReplyToExtension'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Remove-MgGroupAcceptedSenderByRef', 'Remove-MgGroupMemberByRef', 
               'Remove-MgGroupOwnerByRef', 'Remove-MgGroupRejectedSenderByRef'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIoKgYJKoZIhvcNAQcCoIIoGzCCKBcCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBKkcvnYjKhLYim
# W72u1Ie+bEkWWDzM3jUa7pzMKw3CXaCCDXYwggX0MIID3KADAgECAhMzAAAEhV6Z
# 7A5ZL83XAAAAAASFMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjUwNjE5MTgyMTM3WhcNMjYwNjE3MTgyMTM3WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDASkh1cpvuUqfbqxele7LCSHEamVNBfFE4uY1FkGsAdUF/vnjpE1dnAD9vMOqy
# 5ZO49ILhP4jiP/P2Pn9ao+5TDtKmcQ+pZdzbG7t43yRXJC3nXvTGQroodPi9USQi
# 9rI+0gwuXRKBII7L+k3kMkKLmFrsWUjzgXVCLYa6ZH7BCALAcJWZTwWPoiT4HpqQ
# hJcYLB7pfetAVCeBEVZD8itKQ6QA5/LQR+9X6dlSj4Vxta4JnpxvgSrkjXCz+tlJ
# 67ABZ551lw23RWU1uyfgCfEFhBfiyPR2WSjskPl9ap6qrf8fNQ1sGYun2p4JdXxe
# UAKf1hVa/3TQXjvPTiRXCnJPAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUuCZyGiCuLYE0aU7j5TFqY05kko0w
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwNTM1OTAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBACjmqAp2Ci4sTHZci+qk
# tEAKsFk5HNVGKyWR2rFGXsd7cggZ04H5U4SV0fAL6fOE9dLvt4I7HBHLhpGdE5Uj
# Ly4NxLTG2bDAkeAVmxmd2uKWVGKym1aarDxXfv3GCN4mRX+Pn4c+py3S/6Kkt5eS
# DAIIsrzKw3Kh2SW1hCwXX/k1v4b+NH1Fjl+i/xPJspXCFuZB4aC5FLT5fgbRKqns
# WeAdn8DsrYQhT3QXLt6Nv3/dMzv7G/Cdpbdcoul8FYl+t3dmXM+SIClC3l2ae0wO
# lNrQ42yQEycuPU5OoqLT85jsZ7+4CaScfFINlO7l7Y7r/xauqHbSPQ1r3oIC+e71
# 5s2G3ClZa3y99aYx2lnXYe1srcrIx8NAXTViiypXVn9ZGmEkfNcfDiqGQwkml5z9
# nm3pWiBZ69adaBBbAFEjyJG4y0a76bel/4sDCVvaZzLM3TFbxVO9BQrjZRtbJZbk
# C3XArpLqZSfx53SuYdddxPX8pvcqFuEu8wcUeD05t9xNbJ4TtdAECJlEi0vvBxlm
# M5tzFXy2qZeqPMXHSQYqPgZ9jvScZ6NwznFD0+33kbzyhOSz/WuGbAu4cHZG8gKn
# lQVT4uA2Diex9DMs2WHiokNknYlLoUeWXW1QrJLpqO82TLyKTbBM/oZHAdIc0kzo
# STro9b3+vjn2809D0+SOOCVZMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGgowghoGAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAASFXpnsDlkvzdcAAAAABIUwDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEID9AflRnDkvx2cPlkm9z2wCZ
# 0yxz+lZyIMikc/fAMZTYMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEAgzBRl0BGAxO3KRmXvs6zMPwVCa1dFB64NNygSC9I5IA7hOEuW+XSi9OS
# 7Vi2jR3kqWe62TChMIvaaPstqUbc4SSygJAVQIm+Vai6l5tDje8GbampQ2LaR65q
# YeRMc88Ass01u7NfoHzyjQ9C/Ns2iHeFCjb8e27iHWTqKfR59LMw8OjONMWXv//a
# q53HSVMEX7IvC0YR0vY8xgIT/W8jdsIb2Lokcb6hDWCYdMBPScljpQXdbAn4B67t
# 4H+/PhspBBe+08ECwbPPZjnSn90FDLDcp9GJZamqGGMyU9KVL1+XsEQVMHOhRNcL
# pJRoF6i5lxLAjp+GfljgDEeseDqJX6GCF5QwgheQBgorBgEEAYI3AwMBMYIXgDCC
# F3wGCSqGSIb3DQEHAqCCF20wghdpAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFSBgsq
# hkiG9w0BCRABBKCCAUEEggE9MIIBOQIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCCliY1AMCKi4ayGK/qAzBFHG15RcRUmB7ahRkLqqxGlPwIGaTtHpIIo
# GBMyMDI1MTIyMDA3NDM1OC44OTRaMASAAgH0oIHRpIHOMIHLMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1l
# cmljYSBPcGVyYXRpb25zMScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046OTYwMC0w
# NUUwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2Wg
# ghHqMIIHIDCCBQigAwIBAgITMwAAAgTY4A4HlzJYmAABAAACBDANBgkqhkiG9w0B
# AQsFADB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYD
# VQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAeFw0yNTAxMzAxOTQy
# NDdaFw0yNjA0MjIxOTQyNDdaMIHLMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
# aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
# cnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1lcmljYSBPcGVyYXRpb25z
# MScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046OTYwMC0wNUUwLUQ5NDcxJTAjBgNV
# BAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2UwggIiMA0GCSqGSIb3DQEB
# AQUAA4ICDwAwggIKAoICAQDw3Sbcee2d66vkWGTIXhfGqqgQGxQXTnq44XlUvNzF
# St7ELtO4B939jwZFX7DrRt/4fpzGNkFdGpc7EL5S86qKYv360eXjW+fIv1lAqDD3
# 1d/p8Ai9/AZz8M95zo0rDpK2csz9WAyR9FtUDx52VOs9qP3/pgpHvgUvD8s6/3KN
# ITzms8QC1tJ3TMw1cRn9CZgVIYzw2iD/ZvOW0sbF/DRdgM8UdtxjFIKTXTaI/bJh
# sQge3TwayKQ2j85RafFFVCR5/ChapkrBQWGwNFaPzpmYN46mPiOvUxriISC9nQ/G
# rDXUJWzLDmchrmr2baABJevvw31UYlTlLZY6zUmjkgaRfpozd+Glq9TY2E3Dglr6
# PtTEKgPu2hM6v8NiU5nTvxhDnxdmcf8UN7goeVlELXbOm7j8yw1xM9IyyQuUMWko
# rBaN/5r9g4lvYkMohRXEYB0tMaOPt0FmZmQMLBFpNRVnXBTa4haXvn1adKrvTz8V
# lfnHxkH6riA/h2AlqYWhv0YULsEcHnaDWgqA29ry+jH097MpJ/FHGHxk+d9kH2L5
# aJPpAYuNmMNPB7FDTPWAx7Apjr/J5MhUx0i07gV2brAZ9J9RHi+fMPbS+Qm4AonC
# 5iOTj+dKCttVRs+jKKuO63CLwqlljvnUCmuSavOX54IXOtKcFZkfDdOZ7cE4DioP
# 1QIDAQABo4IBSTCCAUUwHQYDVR0OBBYEFBp1dktAcGpW/Km6qm+vu4M1GaJfMB8G
# A1UdIwQYMBaAFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMF8GA1UdHwRYMFYwVKBSoFCG
# Tmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY3JsL01pY3Jvc29mdCUy
# MFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNybDBsBggrBgEFBQcBAQRgMF4w
# XAYIKwYBBQUHMAKGUGh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2Vy
# dHMvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3J0MAwG
# A1UdEwEB/wQCMAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgwDgYDVR0PAQH/BAQD
# AgeAMA0GCSqGSIb3DQEBCwUAA4ICAQBecv6sRw2HTLMyUC1WJJ+FR+DgA9Jkv0lG
# sIt4y69CmOj8R63oFbhSmcdpakxqNbr8v9dyTb4RDyNqtohiiXbtrXmQK5X7y/Q+
# +F0zMotTtTpTPvG3eltyV/LvO15mrLoNQ7W4VH58aLt030tORxs8VnAQQF5BmQQM
# Oua+EQgH4f1F4uF6rl3EC17JBSJ0wjHSea/n0WYiHPR0qkz/NRAf8lSUUV0gbIMa
# wGIjn7+RKyCr+8l1xdNkK/F0UYuX3hG0nE+9Wc0L4A/enluUN7Pa9vOV6Vi3BOJS
# T0RY/ax7iZ45leM8kqCw7BFPcTIkWzxpjr2nCtirnkw7OBQ6FNgwIuAvYNTU7r60
# W421YFOL5pTsMZcNDOOsA01xv7ymCF6zknMGpRHuw0Rb2BAJC9quU7CXWbMbAJLd
# Z6XINKariSmCX3/MLdzcW5XOycK0QhoRNRf4WqXRshEBaY2ymJvHO48oSSY/kpuY
# vBS3ljAAuLN7Rp8jWS7t916paGeE7prmrP9FJsoy1LFKmFnW+vg43ANhByuAEXq9
# Cay5o7K2H5NFnR5wj/SLRKwK1iyUX926i1TEviEiAh/PVyJbAD4koipig28p/6HD
# uiYOZ0wUkm/a5W8orIjoOdU3XsJ4i08CfNp5I73CsvB5QPYMcLpF9NO/1LvoQAw3
# UPdL55M5HTCCB3EwggVZoAMCAQICEzMAAAAVxedrngKbSZkAAAAAABUwDQYJKoZI
# hvcNAQELBQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
# DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
# MjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAy
# MDEwMB4XDTIxMDkzMDE4MjIyNVoXDTMwMDkzMDE4MzIyNVowfDELMAkGA1UEBhMC
# VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
# BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRp
# bWUtU3RhbXAgUENBIDIwMTAwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC
# AQDk4aZM57RyIQt5osvXJHm9DtWC0/3unAcH0qlsTnXIyjVX9gF/bErg4r25Phdg
# M/9cT8dm95VTcVrifkpa/rg2Z4VGIwy1jRPPdzLAEBjoYH1qUoNEt6aORmsHFPPF
# dvWGUNzBRMhxXFExN6AKOG6N7dcP2CZTfDlhAnrEqv1yaa8dq6z2Nr41JmTamDu6
# GnszrYBbfowQHJ1S/rboYiXcag/PXfT+jlPP1uyFVk3v3byNpOORj7I5LFGc6XBp
# Dco2LXCOMcg1KL3jtIckw+DJj361VI/c+gVVmG1oO5pGve2krnopN6zL64NF50Zu
# yjLVwIYwXE8s4mKyzbnijYjklqwBSru+cakXW2dg3viSkR4dPf0gz3N9QZpGdc3E
# XzTdEonW/aUgfX782Z5F37ZyL9t9X4C626p+Nuw2TPYrbqgSUei/BQOj0XOmTTd0
# lBw0gg/wEPK3Rxjtp+iZfD9M269ewvPV2HM9Q07BMzlMjgK8QmguEOqEUUbi0b1q
# GFphAXPKZ6Je1yh2AuIzGHLXpyDwwvoSCtdjbwzJNmSLW6CmgyFdXzB0kZSU2LlQ
# +QuJYfM2BjUYhEfb3BvR/bLUHMVr9lxSUV0S2yW6r1AFemzFER1y7435UsSFF5PA
# PBXbGjfHCBUYP3irRbb1Hode2o+eFnJpxq57t7c+auIurQIDAQABo4IB3TCCAdkw
# EgYJKwYBBAGCNxUBBAUCAwEAATAjBgkrBgEEAYI3FQIEFgQUKqdS/mTEmr6CkTxG
# NSnPEP8vBO4wHQYDVR0OBBYEFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMFwGA1UdIARV
# MFMwUQYMKwYBBAGCN0yDfQEBMEEwPwYIKwYBBQUHAgEWM2h0dHA6Ly93d3cubWlj
# cm9zb2Z0LmNvbS9wa2lvcHMvRG9jcy9SZXBvc2l0b3J5Lmh0bTATBgNVHSUEDDAK
# BggrBgEFBQcDCDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMC
# AYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTV9lbLj+iiXGJo0T2UkFvX
# zpoYxDBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20v
# cGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXRfMjAxMC0wNi0yMy5jcmwwWgYI
# KwYBBQUHAQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpL2NlcnRzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNydDANBgkqhkiG
# 9w0BAQsFAAOCAgEAnVV9/Cqt4SwfZwExJFvhnnJL/Klv6lwUtj5OR2R4sQaTlz0x
# M7U518JxNj/aZGx80HU5bbsPMeTCj/ts0aGUGCLu6WZnOlNN3Zi6th542DYunKmC
# VgADsAW+iehp4LoJ7nvfam++Kctu2D9IdQHZGN5tggz1bSNU5HhTdSRXud2f8449
# xvNo32X2pFaq95W2KFUn0CS9QKC/GbYSEhFdPSfgQJY4rPf5KYnDvBewVIVCs/wM
# nosZiefwC2qBwoEZQhlSdYo2wh3DYXMuLGt7bj8sCXgU6ZGyqVvfSaN0DLzskYDS
# PeZKPmY7T7uG+jIa2Zb0j/aRAfbOxnT99kxybxCrdTDFNLB62FD+CljdQDzHVG2d
# Y3RILLFORy3BFARxv2T5JL5zbcqOCb2zAVdJVGTZc9d/HltEAY5aGZFrDZ+kKNxn
# GSgkujhLmm77IVRrakURR6nxt67I6IleT53S0Ex2tVdUCbFpAUR+fKFhbHP+Crvs
# QWY9af3LwUFJfn6Tvsv4O+S3Fb+0zj6lMVGEvL8CwYKiexcdFYmNcP7ntdAoGokL
# jzbaukz5m/8K6TT4JDVnK+ANuOaMmdbhIurwJ0I9JZTmdHRbatGePu1+oDEzfbzL
# 6Xu/OHBE0ZDxyKs6ijoIYn/ZcGNTTY3ugm2lBRDBcQZqELQdVTNYs6FwZvKhggNN
# MIICNQIBATCB+aGB0aSBzjCByzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
# bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
# b3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEn
# MCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjk2MDAtMDVFMC1EOTQ3MSUwIwYDVQQD
# ExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNloiMKAQEwBwYFKw4DAhoDFQC6
# PYHRw9+9SH+1pwy6qzVG3k9lbqCBgzCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
# IFBDQSAyMDEwMA0GCSqGSIb3DQEBCwUAAgUA7PBRHDAiGA8yMDI1MTIxOTIyMzMw
# MFoYDzIwMjUxMjIwMjIzMzAwWjB0MDoGCisGAQQBhFkKBAExLDAqMAoCBQDs8FEc
# AgEAMAcCAQACAgpLMAcCAQACAhJjMAoCBQDs8aKcAgEAMDYGCisGAQQBhFkKBAIx
# KDAmMAwGCisGAQQBhFkKAwKgCjAIAgEAAgMHoSChCjAIAgEAAgMBhqAwDQYJKoZI
# hvcNAQELBQADggEBAETkvT9Jx5TcEZjJbvbchYhc6EAdDe+t4P4Zf7l3TC4PwBmQ
# ddqowM7cK9uszZYiU+6hCxAdl2AEZo819qJ00KtcNFWrnmxEy8LXTY0pkknKvHVm
# f2+UAsLhKtsJrzmI7IEL9zs49EYhmcIb/ESjqEEQcF4NvmLJF/gEr6fNUJkgnWdv
# ehXdF/VNN5zZJz2Rp44iC7CqZrF/0kQ0mHSo5CXXOtEdryzBDW0vtibNcsQH1v5Q
# PI11uQ34bZ81aWU8iusKMklqcerx8nuJzJGBBQ9kdZwUDw7qZV22duXt0+apotxG
# QSsBKEC1TnZGZmbj7D4hN6o1SQedi20Mr6/eE+gxggQNMIIECQIBATCBkzB8MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNy
# b3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAgTY4A4HlzJYmAABAAACBDAN
# BglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMC8G
# CSqGSIb3DQEJBDEiBCBY33kwlyQ5sJc0KuF5GAUSwaxo7bz0GeYnmR2lBLuStTCB
# +gYLKoZIhvcNAQkQAi8xgeowgecwgeQwgb0EIPnteGX9Wwq8VdJM6mjfx1GEJsu7
# /6kU6l0SS5rcebn+MIGYMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
# c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
# b3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIw
# MTACEzMAAAIE2OAOB5cyWJgAAQAAAgQwIgQgn7J/Wsf4EBd5klMF3gMYOe2XMYu1
# PF7bZLS+TDoyO4gwDQYJKoZIhvcNAQELBQAEggIAU7kwBFzUs6dvpmzBj9n20q9B
# sM/01o09G6v80jVUYfJDH3Jopmgx1EOZHeWs5vDmSGiln47VW9z9f0rnAfMvRoxm
# TXffqrhqZyS2j28pgBL4yzCnTiEkt78Q46Cm+EoISi1HXpGA//5JE/sBI35Qv2vU
# IZ1ARXwXfTbXK56GtcSsHH5kxXCg+Z5gzyTOyDrK5tLiy8PzOwFcyPUThRdX4ssu
# c6t/v42jxXzLeDLHnBHOiOB7aMNyCsQuo4VVOBM76okOj9wEyCsZWTntSWENKsR2
# V+0oyBmoMnzJ7dimdrKCsC4fvkEONNM+wmunEu81p35C/d/TUN9Eq9pHuvj6MYaL
# D+tAw+mhm+7MA3IwoPRKqpvmGZwGdfNjJshvgoF01bsTpwVvuKWamB4clUeFtUr4
# 6vONUHdGNmmFCMpvf7YtPFHwt6ndvOmvpAlT5IAKnTCshYcoX1UDi/DJXIYLtctt
# ltF6xy7zZa58DE4RcwEFrT9LYwYHWigne7MB+230N2fwg7BkxCY0rfnqAJxrNzqy
# kTxGxZfI080N2rqllhAOdc5opQefMWfB2Imvp5ldmOxBlJ6tz52DFer/JBwF42Rf
# Ty9f6cKfWxTaCfcb8eJSrMHS9VNoiNhUzHrsDoLSwD1BKq9Koh9M2jFc6TuouhDO
# tKuak/YXj1t0dN/SWYg=
# SIG # End signature block
